verbose: false
instrumentation:
    root: ./
    default-excludes: true
    excludes: [
        'init.js',
        'client/**/*.js',
        'test/**/*.js',
        'node_modules/**/*.js',
        ]
    embed-source: false
    include-all-sources: true
    variable: __coverage__
    compact: true
    preserve-comments: false
    complete-copy: false
    save-baseline: false
    baseline-file: ./coverage/coverage-baseline.json
reporting:
    print: summary
    reports:
        - lcov
    dir: ./coverage
hooks:
    hook-run-in-context: false
    post-require-hook: null
